### ISSUE TITLE
Add a Search Bar in Explore.ejs

### ISSUE THREAD

**Issue by harshitk075** [opencodeiiita/opencode20-destination-portal#108]
to do:
1.  u just have to  add a form in explore.ejs that will contain a search box and button
   *  search box will be used to search for place <--not to be implemented now.
2. Use bootstrap to beauitify

**Comment by aarpit1010** [comment]
Claim

**Comment by starboi02** [comment]
Claim

**Comment by blaze-assault** [comment]
Claim

**Comment by sarthakm21** [comment]
claim

**Comment by harshitk075** [comment]
assigned to @aarpit1010
