### ISSUE TITLE
README.md file have some documentation mistakes

### ISSUE THREAD

**Issue by rafayhasankhan** [opencodeiiita/opencode20-destination-portal#110]
Mistakes: 
--> The prerequisites heading should have a font size same as Installation Steps heading.
--> The "basic html" words in prerequisites heading list should be in capitalize each word case.
--> The first point in prerequisites heading have punctuation issues like space between words after commas.
--> The word forking in the Installation steps heading should be in capitalize case.
--> Point 3 and 4 are commands only for linux/ubuntu OS.
--> Point 5 should be sentence capitalized case.
--> Point 5 is sub points are not defined specifically.

**Comment by blaze-assault** [comment]
Claim

**Comment by aarpit1010** [comment]
Claim

**Comment by garvitchittora** [comment]
claim

**Comment by blaze-assault** [comment]
please assign the issue .and add points label to task @rafayhasankhan .

**Comment by harshitk075** [comment]
assigned to @blaze-assault

**Comment by aarpit1010** [comment]
@harshitk075  Sir, it's been 2 days since issue has been assigned and no PR has been made. Could you assign it to the next person who claimed the issue?

**Comment by blaze-assault** [comment]
I still have time .
![](https://imgur.com/a/RckodLL)

**Comment by rafayhasankhan** [comment]
@harshitk075 Can you assign this issue to me .?

**Comment by blaze-assault** [comment]
@harshitk075  please review the pr
