### ISSUE TITLE
create a Footer for index page with social media widgets(ref image in desc )

### ISSUE THREAD

**Issue by harshitk075** [opencodeiiita/opencode20-destination-portal#20]
>Footer should look like as shown in the linked image
https://www.orbitmedia.com/wp-content/uploads/2015/11/social.png
>set background color as Dark

**Comment by sandy9808** [comment]
claim

**Comment by sanskar-p** [comment]
claim

**Comment by sarthakm21** [comment]
claim

**Comment by harshitk075** [comment]
@sandy9808  go ahead!!!

**Comment by JLodha** [comment]
Claim

**Comment by iit2019017** [comment]
claim

**Comment by Piyush4064** [comment]
can I work on this task?

**Comment by sggts04** [comment]
can I work on this? @harshitk075 its been 2 days

**Comment by JLodha** [comment]
I want to work on this.
It's already been 2 days since it has been assigned to sandy9808

**Comment by infern018** [comment]
Claim

**Comment by harshitk075** [comment]
assigned to @sanskar-p

**Comment by garvitchittora** [comment]
claim

**Comment by cyber-venom003** [comment]
__CLAIM__

**Comment by sanskar-p** [comment]
> assigned to @sanskar-p

Sorry. I missed this notification. I'll get on it right away.
