### ISSUE TITLE
Find an attractive logo for website and place it in the jumbotron

### ISSUE THREAD

**Issue by harshitk075** [opencodeiiita/opencode20-destination-portal#4]
go for this issue only after completing  issue 1(getting PR merged)

**Comment by padityak79** [comment]
claim

**Comment by blaze-assault** [comment]
Claim

**Comment by sandy9808** [comment]
claim

**Comment by infern018** [comment]
claim

**Comment by ananya-mohanty** [comment]
claim

**Comment by harshitk075** [comment]
go ahead @infern018

**Comment by blaze-assault** [comment]
Sir my comment for claim is at top.

**Comment by harshitk075** [comment]
> Sir my comment for claim is at top.

but you haven't completed issue 1 which is required for this issue.That's i assigned to other guy

**Comment by infern018** [comment]
Sir I just have to create a **.jumbotron** element in **base.css** and add the logo in it or also add some text regarding website?
