### ISSUE TITLE
design a new login template and write a GET route for it in app.js

### ISSUE THREAD

**Issue by harshitk075** [opencodeiiita/opencode20-destination-portal#42]
## things to do:
1-> design a login template (login.ejs) 
2-> write a get route for it in app.js (google for how to write nodejs route)
        --> route will be used for rendering the login.ejs
3-> place a Login and signup link in the Navbar of  index.js

* NOTE  : No authentication to be added  for login for this issue.

**Comment by sggts04** [comment]
claim

**Comment by harshitk075** [comment]
Update: The points for this task is changed from 50 to 30 for some reason
assigned to : @sggts04

**Comment by JLodha** [comment]
claim
