### ISSUE TITLE
set a suitable image as jumbotron(banner) background with dynamic effects 

### ISSUE THREAD

**Issue by harshitk075** [opencodeiiita/opencode20-destination-portal#51]
for example of dynamic effects refer to:
https://codepen.io/xposedbones/pen/XXpgpj

**Comment by pavikachaudhary** [comment]
claim

**Comment by griffy06** [comment]
Since the everyone label is removed, can I claim this?

**Comment by 2802harsh** [comment]
claim

**Comment by harshitk075** [comment]
> Since the everyone label is removed, can I claim this?

@griffy06  go ahead!!
