### ISSUE TITLE
Add a Preloader to the website

### ISSUE THREAD

**Issue by harshitk075** [opencodeiiita/opencode20-destination-portal#69]

**Comment by sanskar-p** [comment]
claim

**Comment by cyber-venom003** [comment]
__CLAIM__

**Comment by sarthakm21** [comment]
Claim

**Comment by pradhuman1** [comment]
claim

**Comment by harshitk075** [comment]
assigned to @cyber-venom003

**Comment by cyber-venom003** [comment]
@harshitk075 Sir can you please guide me why these errors are coming???
![error](https://user-images.githubusercontent.com/58390399/73009756-24d0ab80-3e37-11ea-8196-07edd07e8b7d.png)

**Comment by harshitk075** [comment]
> @harshitk075 Sir can you please guide me why these errors are coming???
> ![error](https://user-images.githubusercontent.com/58390399/73009756-24d0ab80-3e37-11ea-8196-07edd07e8b7d.png)

Do one thing change the CDN of jquery in the footer.ejs from slim to uncompressed.
go to https://code.jquery.com/.
Animations are not included in slim version of CDN

**Comment by harshitk075** [comment]
did it work @cyber-venom003

**Comment by cyber-venom003** [comment]
> did it work @cyber-venom003

Trying sir....please give me some time

**Comment by harshitk075** [comment]
assigned to @sarthakm21

**Comment by harshitk075** [comment]
reassigned to @sarthakm21

**Comment by Rohini13** [comment]
Claim
