### ISSUE TITLE
Add favicon/icon on all Navbars

### ISSUE THREAD

**Issue by harshitk075** [opencodeiiita/opencode20-destination-portal#84]

**Comment by blaze-assault** [comment]
Claim

**Comment by pradhuman1** [comment]
claim

**Comment by harshitk075** [comment]
assigned to @blaze-assault

**Comment by JLodha** [comment]
Claim

**Comment by blaze-assault** [comment]
@harshitk075  sir which icon to add.. please  clarify i will make pr by tonight

**Comment by cyber-venom003** [comment]
__CLAIM__

**Comment by sarthakm21** [comment]
Claim

**Comment by harshitk075** [comment]
> @harshitk075 sir which icon to add.. please clarify i will make pr by tonight

pick any suitable icon for Navbar Logo section..

**Comment by blaze-assault** [comment]
Ok sir i will do it by tomorrow.i need extra time as task was not clear
.and  answer to doubt was not replied on time due to obvious reasons
