### ISSUE TITLE
Implement an API for the website

### ISSUE THREAD

**Issue by harshitk075** [opencodeiiita/opencode20-destination-portal#95]
### things to do:
1. Find an API whichever suitable related to destination portal.
2. The API should be able to find Tourist places for say a country, city etc.
3. More features are appreciable.
4. show basic implementation of the API using our own creativity.

**Comment by garvitchittora** [comment]
claim

**Comment by blaze-assault** [comment]
Claim

**Comment by sggts04** [comment]
claim

**Comment by harshitk075** [comment]
assigned to @garvitchittora

**Comment by harshitk075** [comment]
@garvitchittora  status????

**Comment by sggts04** [comment]
Can I work on this?

**Comment by sggts04** [comment]
Can I work on this? Its been 3 days

**Comment by blaze-assault** [comment]
I was the second one to claim it .it has been three days .can i claim it

**Comment by harshitk075** [comment]
The issue will be reassigned if reply is not given @garvitchittora  by tomorrow.

**Comment by harshitk075** [comment]
assigned to @blaze-assault

**Comment by sggts04** [comment]
Can I work on this?

**Comment by sggts04** [comment]
@harshitk075

**Comment by harshitk075** [comment]
go on @sggts04
