### ISSUE TITLE
Set given Image as background cover for addplaceform template with appropriate transparency

### ISSUE THREAD

**Issue by harshitk075** [opencodeiiita/opencode20-destination-portal#98]
Image URL : https://images.unsplash.com/photo-1467377791767-c929b5dc9a23?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1189&q=80

### You can make necessary changes to form if required

**Comment by blaze-assault** [comment]
Claim

**Comment by harshitk075** [comment]
assigned to @blaze-assault

**Comment by sarthakm21** [comment]
Claim
